[deps]
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ELFINData = "fcbbe0ba-d66e-4e8f-95dd-8166f95b70c5"
PySPEDAS = "668d2cef-03a7-4c36-a521-7d1c6ddc8846"
SpacePhysicsMakie = "0c28ffd8-ae30-4a56-b2e4-f8332c621ad2"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[sources]
ELFINData = {path = ".."}
